### ISSUE TITLE
PHP Warning: Undefined array key in CollapsibleAccordion.php

### ISSUE THREAD

**Issue by kunoFM** [t3solution/t3sbootstrap#295]
With Typo3 11.5.21, PHP8.2 und t3sbootstrap 5.2.8 I get the following error messages:

- Core: Error handler (FE): PHP Warning: Undefined array key "appearance" in /var/www/html/typo3conf/ext/t3sbootstrap/Classes/Wrapper/CollapsibleAccordion.php line 30

- Core: Error handler (FE): PHP Warning: Undefined array key "alwaysOpen" in /var/www/html/typo3conf/ext/t3sbootstrap/Classes/Wrapper/CollapsibleAccordion.php line 34

- Core: Error handler (FE): PHP Warning: Undefined array key "appearance" in /var/www/html/typo3conf/ext/t3sbootstrap/Classes/Wrapper/CollapsibleAccordion.php line 39

**Comment by peterschoene** [comment]
I get the errors above with an installation of
TYPO3 V 12.4.20
T3S 5.3.15

Could you please provide the solution?

+ I don't understand where to get t3sb_package v1.0.2 via composer? Or shall I install this manually?

**Comment by t3solution** [comment]
I cannot understand the error. 
But if you open and save the “Collapsible Container” and the “Collapsible Elements”, the error message should disappear.

The t3sb_package is not available via composer.
Otherwise you would overwrite it with every “composer update”. So you have to install the package as a local extension.
